name: Linter status

on:
  push
  pull_request

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install, build
        run: |
          make install
          make build
        env:
          CI: truel
    - name: Run linter
      run: make lint
    - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
